import type { Metadata } from "next";
import { Share_Tech_Mono } from "next/font/google";
import "./globals.css";

const share_tech_mono = Share_Tech_Mono({ weight: ["400"], subsets: ["latin"] });

const metadata: Metadata = {
	title: "Jake Cordal Tattoo",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body className={share_tech_mono.className}>{children}</body>
		</html>
	);
};

export default RootLayout;
export { metadata };
