import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"] });

const metadata: Metadata = {
	title: "Jake Cordal Tattoo",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<html lang="en">
			<body className={raleway.className}>{children}</body>
		</html>
	);
};

export default RootLayout;
export { metadata };
